### ISSUE TITLE
Postinstall is obsolete, can't finish Discourse setup

### ISSUE THREAD

**Issue by HLFH** [rumpelsepp/aur-packages#2]
Related to: https://bbs.archlinux.org/viewtopic.php?id=198939

Instead of:

```bash
[root@arch-server discourse]# sudo -u discourse -s /usr/bin/bash -c "cd /usr/share/webapps/discourse; bundle exec rake discourse:setup RAILS_ENV=production"
```
as seen here: https://aur.archlinux.org/cgit/aur.git/tree/discourse.install?h=discourse
and btw, it's not discourse.config but discourse.conf

I did:

```bash
[root@arch-server discourse]# sudo -u discourse -s /usr/bin/bash -c "cd /usr/share/webapps/discourse; bundle exec rake db:create --trace RAILS_ENV=production"
** Invoke db:create (first_time)
** Invoke db:load_config (first_time)
** Execute db:load_config
** Execute db:create
```

But then 

```bash
[root@arch-server discourse]# sudo -u discourse -s /usr/bin/bash -c "cd /usr/share/webapps/discourse; bundle exec rake db:migrate db:test:prepare db:seed_fu --trace RAILS_ENV=production"
** Invoke db:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
Failed to report error: Name or service not known 2 Name or service not known subscribe failed, reconnecting in 1 second. Call stack ["/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gem
s/redis-3.2.1/lib/redis/connection/hiredis.rb:17:in `connect'", "/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/redis-3.2.1/lib/redis/connection/hiredis.rb:17:in `connect'", "/usr/
share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/redis-3.2.1/lib/redis/client.rb:322:in `establish_connection'", "/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/redis-3.2.1/li
b/redis/client.rb:94:in `block in connect'", "/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/redis-3.2.1/lib/redis/client.rb:279:in `with_reconnect'", "/usr/share/webapps/discourse
/vendor/bundle/ruby/2.3.0/gems/redis-3.2.1/lib/redis/client.rb:93:in `connect'", "/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/redis-3.2.1/lib/redis/client.rb:262:in `with_socket
_timeout'", "/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/redis-3.2.1/lib/redis/client.rb:273:in `without_socket_timeout'", "/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0
/gems/redis-3.2.1/lib/redis/client.rb:125:in `call_loop'", "/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/redis-3.2.1/lib/redis/subscribe.rb:35:in `subscription'", "/usr/share/web
apps/discourse/vendor/bundle/ruby/2.3.0/gems/redis-3.2.1/lib/redis/subscribe.rb:12:in `subscribe'", "/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/redis-3.2.1/lib/redis.rb:2622:in
 `_subscription'", "/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/redis-3.2.1/lib/redis.rb:2035:in `block in subscribe'", "/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/ge
ms/redis-3.2.1/lib/redis.rb:37:in `block in synchronize'", "/usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'", "/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/redis-3.2.1/li
b/redis.rb:37:in `synchronize'", "/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/redis-3.2.1/lib/redis.rb:2034:in `subscribe'", "/usr/share/webapps/discourse/vendor/bundle/ruby/2.3
.0/gems/message_bus-1.0.16/lib/message_bus/redis/reliable_pub_sub.rb:302:in `global_subscribe'", "/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/message_bus-1.0.16/lib/message_bus.
rb:457:in `global_subscribe_thread'", "/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/message_bus-1.0.16/lib/message_bus.rb:409:in `block in new_subscriber_thread'"]
URGENT: Name or service not known Failed to initialize site default
Failed to report error: Name or service not known 2 Name or service not known subscribe failed, reconnecting in 1 second. Call stack ["/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gem
s/redis-3.2.1/lib/redis/connection/hiredis.rb:17:in `connect'", "/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/redis-3.2.1/lib/redis/connection/hiredis.rb:17:in `connect'", "/usr/
share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/redis-3.2.1/lib/redis/client.rb:322:in `establish_connection'", "/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/redis-3.2.1/li
b/redis/client.rb:94:in `block in connect'", "/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/redis-3.2.1/lib/redis/client.rb:279:in `with_reconnect'", "/usr/share/webapps/discourse
/vendor/bundle/ruby/2.3.0/gems/redis-3.2.1/lib/redis/client.rb:93:in `connect'", "/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/redis-3.2.1/lib/redis/client.rb:262:in `with_socket
_timeout'", "/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/redis-3.2.1/lib/redis/client.rb:273:in `without_socket_timeout'", "/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0
/gems/redis-3.2.1/lib/redis/client.rb:125:in `call_loop'", "/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/redis-3.2.1/lib/redis/subscribe.rb:35:in `subscription'", "/usr/share/web
apps/discourse/vendor/bundle/ruby/2.3.0/gems/redis-3.2.1/lib/redis/subscribe.rb:12:in `subscribe'", "/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/redis-3.2.1/lib/redis.rb:2622:in
 `_subscription'", "/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/redis-3.2.1/lib/redis.rb:2035:in `block in subscribe'", "/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/ge
ms/redis-3.2.1/lib/redis.rb:37:in `block in synchronize'", "/usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'", "/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/redis-3.2.1/li
b/redis.rb:37:in `synchronize'", "/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/redis-3.2.1/lib/redis.rb:2034:in `subscribe'", "/usr/share/webapps/discourse/vendor/bundle/ruby/2.3
.0/gems/message_bus-1.0.16/lib/message_bus/redis/reliable_pub_sub.rb:302:in `global_subscribe'", "/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/message_bus-1.0.16/lib/message_bus.
rb:457:in `global_subscribe_thread'", "/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/message_bus-1.0.16/lib/message_bus.rb:409:in `block in new_subscriber_thread'"]
Failed to report error: Name or service not known 3 PG::UndefinedTable: ERREUR:  la relation « users » n'existe pas
LINE 5:                WHERE a.attrelid = '"users"'::regclass
                                          ^
:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
                FROM pg_attribute a LEFT JOIN pg_attrdef d
                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
               WHERE a.attrelid = '"users"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum

Please require the stackprof gem falling back to fast_stack
rake aborted!
LoadError: cannot load such file -- memory_profiler
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/activesupport-4.1.10/lib/active_support/dependencies.rb:247:in `require'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/activesupport-4.1.10/lib/active_support/dependencies.rb:247:in `block in require'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/activesupport-4.1.10/lib/active_support/dependencies.rb:232:in `load_dependency'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/activesupport-4.1.10/lib/active_support/dependencies.rb:247:in `require'
/usr/share/webapps/discourse/config/initializers/06-mini_profiler.rb:7:in `<top (required)>'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/activesupport-4.1.10/lib/active_support/dependencies.rb:241:in `load'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/activesupport-4.1.10/lib/active_support/dependencies.rb:241:in `block in load'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/activesupport-4.1.10/lib/active_support/dependencies.rb:232:in `load_dependency'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/activesupport-4.1.10/lib/active_support/dependencies.rb:241:in `load'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/railties-4.1.10/lib/rails/engine.rb:648:in `block in load_config_initializer'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/activesupport-4.1.10/lib/active_support/notifications.rb:161:in `instrument'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/railties-4.1.10/lib/rails/engine.rb:647:in `load_config_initializer'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/railties-4.1.10/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/railties-4.1.10/lib/rails/engine.rb:611:in `each'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/railties-4.1.10/lib/rails/engine.rb:611:in `block in <class:Engine>'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/railties-4.1.10/lib/rails/initializable.rb:30:in `instance_exec'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/railties-4.1.10/lib/rails/initializable.rb:30:in `run'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/railties-4.1.10/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
/usr/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/usr/lib/ruby/2.3.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
/usr/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
/usr/lib/ruby/2.3.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/railties-4.1.10/lib/rails/initializable.rb:44:in `each'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/railties-4.1.10/lib/rails/initializable.rb:44:in `tsort_each_child'
/usr/lib/ruby/2.3.0/tsort.rb:415:in `call'
/usr/lib/ruby/2.3.0/tsort.rb:415:in `each_strongly_connected_component_from'
/usr/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
/usr/lib/ruby/2.3.0/tsort.rb:347:in `each'
/usr/lib/ruby/2.3.0/tsort.rb:347:in `call'
/usr/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
/usr/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
/usr/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/railties-4.1.10/lib/rails/initializable.rb:54:in `run_initializers'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/railties-4.1.10/lib/rails/application.rb:300:in `initialize!'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/railties-4.1.10/lib/rails/railtie.rb:194:in `public_send'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/railties-4.1.10/lib/rails/railtie.rb:194:in `method_missing'
/usr/share/webapps/discourse/config/environment.rb:5:in `<top (required)>'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/activesupport-4.1.10/lib/active_support/dependencies.rb:247:in `require'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/activesupport-4.1.10/lib/active_support/dependencies.rb:247:in `block in require'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/activesupport-4.1.10/lib/active_support/dependencies.rb:232:in `load_dependency'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/activesupport-4.1.10/lib/active_support/dependencies.rb:247:in `require'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/railties-4.1.10/lib/rails/application.rb:276:in `require_environment!'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/railties-4.1.10/lib/rails/application.rb:405:in `block in run_tasks_blocks'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:201:in `block in invoke_prerequisites'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:199:in `each'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:199:in `invoke_prerequisites'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/bin/rake:23:in `load'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/bin/rake:23:in `<main>'
Tasks: TOP => db:migrate => environment
```

**Comment by HLFH** [comment]
```bash
systemctl stop postgresql
su - postgres
initdb --locale en_US.UTF-8 -E UTF8 -D '/var/lib/postgres/data'
exit
systemctl start postgresql
```

And according to: https://github.com/discourse/discourse/blob/master/docs/DEVELOPER-ADVANCED.md

First steps don't seem to be needed here.

```bash
cd /usr/share/webapps/discourse
sudo -u discourse bundle install
systemctl start redis
```

but still:

```bash
[root@arch-server discourse]#  bundle exec rake db:create db:migrate db:test:prepare --trace
rake aborted!
LoadError: cannot load such file -- qunit-rails
/usr/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `require'
/usr/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `block (2 levels) in require'
/usr/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
/usr/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
/usr/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
/usr/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
/usr/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
/usr/share/webapps/discourse/config/application.rb:15:in `<top (required)>'
/usr/share/webapps/discourse/Rakefile:5:in `require'
/usr/share/webapps/discourse/Rakefile:5:in `<top (required)>'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/rake-10.4.2/lib/rake/rake_module.rb:28:in `load'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/rake-10.4.2/lib/rake/rake_module.rb:28:in `load_rakefile'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:689:in `raw_load_rakefile'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:94:in `block in load_rakefile'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:93:in `load_rakefile'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:77:in `block in run'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/bin/rake:23:in `load'
/usr/share/webapps/discourse/vendor/bundle/ruby/2.3.0/bin/rake:23:in `<main>'
```

**Comment by HLFH** [comment]
Dramatically fixed. I know quite how but too complicated to document it!

**Comment by rumpelsepp** [comment]
And what I am supposed to do? What's the actual problem?

**Comment by HLFH** [comment]
For various reasons, I can't run `sudo -u discourse -s /usr/bin/bash -c "cd /srv/http/discourse; bundle exec rake db:create db:migrate db:test:prepare RAILS_ENV=production"` until the end with 1.4.3, 1.5.0.beta7, and even the master version. So, I'll retry 1.3.2.

**Comment by rumpelsepp** [comment]
Have you tried `systemctl start discourse-update.service`? I do this every few months and it have been worked well the whole time.

**Comment by HLFH** [comment]
In fact, even with 1.3.2, I get:

```bash
== Seed from /srv/http/discourse/db/fixtures/500_lounge_category.rb

== Seed from /srv/http/discourse/db/fixtures/501_meta_category.rb

== Seed from /srv/http/discourse/db/fixtures/502_staff_category.rb

== Seed from /srv/http/discourse/db/fixtures/999_settings.rb

== Seed from /srv/http/discourse/db/fixtures/999_topics.rb
rake aborted!
NoMethodError: undefined method `[]' for nil:NilClass
/srv/http/discourse/vendor/bundle/ruby/2.3.0/gems/activerecord-4.1.10/lib/active_record/tasks/database_tasks.rb:144:in `purge'
/srv/http/discourse/vendor/bundle/ruby/2.3.0/gems/activerecord-4.1.10/lib/active_record/railties/databases.rake:347:in `block (3 levels) in <top (required)>'
/srv/http/discourse/vendor/bundle/ruby/2.3.0/gems/activerecord-4.1.10/lib/active_record/railties/databases.rake:353:in `block (3 levels) in <top (required)>'
Tasks: TOP => db:test:load => db:test:purge
(See full trace by running task with --trace)
[root@arch-server discourse]#
```

**Comment by rumpelsepp** [comment]
I hate that rails crap. Have you tried the manual way using "bundle install --path vendor bundle"?

**Comment by HLFH** [comment]
I'm getting the last issue after `sudo -u discourse -s /usr/bin/bash -c "cd /srv/http/discourse; bundle exec rake db:create db:migrate db:test:prepare RAILS_ENV=production"`. Btw, ` sudo -u discourse -s /usr/bin/bash -c "cd /srv/http/discourse; bundle install --no-cache --no-prune --deployment --without development test"` is running ok.

**Comment by HLFH** [comment]
@rumpelsepp I posted there: https://meta.discourse.org/t/nomethoderror-undefined-method-for-nil-nilclass/37647 ; thanks for everything!

**Comment by rumpelsepp** [comment]
Do net expect that much help from upstream, as they sadly only support their docker crap. :(

**Comment by HLFH** [comment]
@rumpelsepp `Docker crap`, `Ruby on Rails crap`. I'm happy you agree with me. Thanks for everything and have a really good day!! :)

**Comment by rumpelsepp** [comment]
I have nothing against developing using Ruby and Rails; but quite frankly, packaging and deploying such software is a *nightmare*.
